swagger: "2.0"
info:
  version: "1.0.0"
  title: "Us cities API"
host: "localhost:3000"
tags:
  - name: "states"
  - name: "counties"
  - name: "search"
schemes:
  - "http"
paths:
  /states:
    get:
      tags:
        - "states"
      summary: "Get list of states, counties array is always empty"
      operationId: "getStates"
      responses:
        "200":
          description: "OK"
      produces:
        - "application/json"
  /states/{stateId}/counties:
    get:
      tags:
        - "states"
      parameters:
        - name: "stateId"
          in: "path"
          description: "ID of the state"
          required: true
          type: "string"
      summary: "Get list of counties for given state, cities array is always empty"
      operationId: "getStateCounties"
      responses:
        "200":
          description: "OK"
      produces:
        - "application/json"
  /counties/{countyId}/cities:
    get:
      tags:
        - "counties"
      parameters:
        - name: "countyId"
          in: "path"
          description: "ID of the state"
          required: true
          type: "string"
      summary: "Get list of cities for given county"
      operationId: "getCountyCities"
      responses:
        "200":
          description: "OK"
      produces:
        - "application/json"
  /search/{term}:
    get:
      tags:
        - "search"
      parameters:
        - name: "term"
          in: "path"
          description: "Search term"
          required: true
          type: "string"
      summary: "Get full tree structure for given term. Does a full text search in city, county and state name."
      operationId: "search"
      responses:
        "200":
          description: "OK"
      produces:
        - "application/json"
